# Generated by Django 6.0.3 on 2026-04-21 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e hora')),
                ('tipo', models.CharField(choices=[('criacao', 'Criação'), ('remocao', 'Remoção'), ('edicao', 'Edição'), ('alteracao', 'Alteração')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('modulo', models.CharField(db_index=True, help_text='Código do módulo (ex.: membros, tesouraria).', max_length=32, verbose_name='Módulo')),
                ('detalhes', models.TextField(verbose_name='Detalhes')),
                ('objeto_tipo', models.CharField(blank=True, help_text='Ex.: membros.Membro', max_length=120, verbose_name='Tipo de objeto')),
                ('objeto_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='ID do objeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Registo de auditoria',
                'verbose_name_plural': 'Registos de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
