# Generated by Django 6.0.3 on 2026-04-14 00:10

import django.db.models.deletion
import membros.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('nome_conhecido', models.CharField(blank=True, max_length=120, verbose_name='Nome conhecido')),
                ('cpf', models.CharField(blank=True, help_text='Armazenado somente com números; use a máscara no formulário.', max_length=11, null=True, unique=True, validators=[membros.validators.validate_cpf_digits], verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('data_casamento', models.DateField(blank=True, null=True, verbose_name='Data de casamento')),
                ('batizado', models.BooleanField(default=False, verbose_name='É batizado(a)?')),
                ('data_batismo', models.DateField(blank=True, null=True, verbose_name='Data de batismo')),
                ('locomocao', models.CharField(blank=True, choices=[('pe', 'A pé'), ('carro', 'Carro'), ('moto', 'Moto'), ('bicicleta', 'Bicicleta'), ('apps', 'Apps'), ('outro', 'Outro')], max_length=20, verbose_name='Locomoção')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='membros/fotos/', verbose_name='Foto')),
                ('casado_com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parceiros', to='membros.membro', verbose_name='Casado(a) com')),
                ('filhos', models.ManyToManyField(blank=True, help_text='Outros membros cadastrados como filhos.', related_name='pais', to='membros.membro', verbose_name='Filhos(as)')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome_completo'],
            },
        ),
    ]
