# Generated by Django 6.0.3 on 2026-04-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='nome_conhecido',
            field=models.CharField(blank=True, max_length=120, verbose_name='Conhecido por'),
        ),
    ]
