# Generated by Django 6.0.3 on 2026-04-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_alter_nome_conhecido_verbose_colon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
    ]
