# Generated by Django 6.0.3 on 2026-04-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_membro_sexo_obrigatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União estável'), ('separado', 'Separado(a)'), ('outro', 'Outro')], max_length=20, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='membro',
            name='ministerios',
            field=models.TextField(blank=True, help_text='Participação em ministérios ou equipes.', verbose_name='Ministérios'),
        ),
        migrations.AddField(
            model_name='membro',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
