# Generated by Django 6.0.3 on 2026-04-14 01:18

import membros.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0005_membro_estado_civil_obs_ministerios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[membros.validators.validate_cpf_digits], verbose_name='CPF'),
        ),
    ]
