# Generated by Django 6.0.3 on 2026-04-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0012_locomocao_tamanhocamisa_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, help_text='Se desmarcado, o membro deixa de aparecer em listas e pesquisas na aplicação; o registo permanece na base de dados.', verbose_name='Ativo no cadastro'),
        ),
    ]
