from django.urls import path

from . import views

app_name = 'tesouraria'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'membros/autocomplete/lancamento/',
        views.membro_autocomplete_lancamento,
        name='membro_autocomplete_lancamento',
    ),
    path(
        'categorias/lista/',
        views.categorias_lista_partial,
        name='categorias_lista',
    ),
    path(
        'categorias/modal/nova/',
        views.categoria_modal_criar,
        name='categoria_modal_criar',
    ),
    path('categorias/nova/', views.categoria_criar, name='categoria_criar'),
    path(
        'categorias/<int:pk>/modal/editar/',
        views.categoria_modal_editar,
        name='categoria_modal_editar',
    ),
    path(
        'categorias/<int:pk>/modal/excluir/',
        views.categoria_modal_excluir,
        name='categoria_modal_excluir',
    ),
    path(
        'categorias/<int:pk>/salvar/',
        views.categoria_salvar,
        name='categoria_salvar',
    ),
    path(
        'categorias/<int:pk>/excluir/',
        views.categoria_excluir,
        name='categoria_excluir',
    ),
    path('categorias/', views.categorias_index, name='categorias_index'),
    path(
        'eventos/lista/',
        views.eventos_lista_partial,
        name='eventos_lista',
    ),
    path(
        'eventos/modal/novo/',
        views.evento_modal_criar,
        name='evento_modal_criar',
    ),
    path('eventos/novo/', views.evento_criar, name='evento_criar'),
    path(
        'eventos/<int:pk>/modal/editar/',
        views.evento_modal_editar,
        name='evento_modal_editar',
    ),
    path(
        'eventos/<int:pk>/modal/excluir/',
        views.evento_modal_excluir,
        name='evento_modal_excluir',
    ),
    path(
        'eventos/<int:pk>/salvar/',
        views.evento_salvar,
        name='evento_salvar',
    ),
    path(
        'eventos/<int:pk>/excluir/',
        views.evento_excluir,
        name='evento_excluir',
    ),
    path('eventos/', views.eventos_index, name='eventos_index'),
    path('competencias/', views.competencias_lista_partial, name='competencias_lista'),
    path(
        'competencias/modal/nova/',
        views.competencia_modal_criar,
        name='competencia_modal_criar',
    ),
    path('competencias/nova/', views.competencia_criar, name='competencia_criar'),
    path(
        'competencias/<int:competencia_pk>/contas/modal/nova/',
        views.conta_modal_criar,
        name='conta_modal_criar',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/nova/',
        views.conta_criar,
        name='conta_criar',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/lista/',
        views.lancamentos_lista_partial,
        name='lancamentos_lista',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/preservar-e-nova-categoria/',
        views.lancamento_preservar_rascunho_abrir_categoria,
        name='lancamento_preservar_rascunho_abrir_categoria',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/restaurar-rascunho/',
        views.lancamento_restaurar_rascunho_modal,
        name='lancamento_restaurar_rascunho_modal',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/modal/entrada/',
        views.lancamento_modal_entrada,
        name='lancamento_modal_entrada',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/entrada/',
        views.lancamento_criar_entrada,
        name='lancamento_criar_entrada',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/modal/saida/',
        views.lancamento_modal_saida,
        name='lancamento_modal_saida',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/saida/',
        views.lancamento_criar_saida,
        name='lancamento_criar_saida',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/<int:pk>/modal/editar/',
        views.lancamento_modal_editar,
        name='lancamento_modal_editar',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/<int:pk>/salvar/',
        views.lancamento_salvar,
        name='lancamento_salvar',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/<int:pk>/modal/excluir/',
        views.lancamento_modal_excluir,
        name='lancamento_modal_excluir',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/lancamentos/<int:pk>/excluir/',
        views.lancamento_excluir,
        name='lancamento_excluir',
    ),
    path(
        'competencias/<int:competencia_pk>/contas/<int:conta_pk>/',
        views.conta_detalhe,
        name='conta_detalhe',
    ),
    path(
        'competencias/<int:pk>/modal/editar/',
        views.competencia_modal_editar,
        name='competencia_modal_editar',
    ),
    path(
        'competencias/<int:pk>/modal/excluir/',
        views.competencia_modal_excluir,
        name='competencia_modal_excluir',
    ),
    path(
        'competencias/<int:pk>/salvar/',
        views.competencia_salvar,
        name='competencia_salvar',
    ),
    path(
        'competencias/<int:pk>/excluir/',
        views.competencia_excluir,
        name='competencia_excluir',
    ),
    path(
        'competencias/<int:pk>/continua/',
        views.competencia_definir_continua,
        name='competencia_definir_continua',
    ),
    path(
        'competencias/<int:pk>/relatorio-pdf/',
        views.competencia_relatorio_pdf,
        name='competencia_relatorio_pdf',
    ),
    path(
        'competencias/<int:pk>/',
        views.competencia_detalhe,
        name='competencia_detalhe',
    ),
]
