# Generated by Django 6.0.3 on 2026-04-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0006_competenciatesouraria_continua'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='eventos',
            field=models.ManyToManyField(blank=True, related_name='lancamentos', to='tesouraria.eventofinanceiro', verbose_name='Eventos'),
        ),
    ]
