# Generated by Django 6.0.3 on 2026-04-21 04:32

import django.db.models.deletion
from django.db import migrations, models


def copy_m2m_evento_para_fk(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT lancamentofinanceiro_id, MIN(eventofinanceiro_id)
            FROM tesouraria_lancamentofinanceiro_eventos
            GROUP BY lancamentofinanceiro_id
            """
        )
        rows = cursor.fetchall()
    Lancamento = apps.get_model('tesouraria', 'LancamentoFinanceiro')
    for lid, eid in rows:
        Lancamento.objects.filter(pk=lid).update(evento_id=eid)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0007_eventos_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='evento',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lancamentos',
                to='tesouraria.eventofinanceiro',
                verbose_name='Evento',
            ),
        ),
        migrations.RunPython(copy_m2m_evento_para_fk, noop),
        migrations.RemoveField(
            model_name='lancamentofinanceiro',
            name='eventos',
        ),
    ]
