# Generated by Django 6.0.3 on 2026-06-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros', '0013_membro_ativo_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo no cadastro')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('nome_conhecido', models.CharField(blank=True, max_length=120, verbose_name='Conhecido por')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('conheceu_por', models.CharField(blank=True, choices=[('culto_familia', 'Culto Família'), ('culto_jovem', 'Culto Jovem'), ('eventos', 'Eventos'), ('grupos', 'Grupos'), ('instagram', 'Instagram'), ('outro', 'Outro')], max_length=30, verbose_name='Conheceu a igreja por')),
                ('convertido', models.BooleanField(default=False, verbose_name='É convertido?')),
                ('batizado', models.BooleanField(default=False, verbose_name='É batizado?')),
                ('denominacao', models.CharField(blank=True, max_length=180, verbose_name='Denominação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Obs')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora do cadastro')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que cadastrou')),
                ('membro_acompanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes_acompanhados', to='membros.membro', verbose_name='Membro que acompanha')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'ordering': ['nome_completo'],
            },
        ),
    ]
