# Generated by Django 6.0.3 on 2026-04-21 00:40

from django.db import migrations, models


def seed_perfil_membros_editor(apps, schema_editor):
    """Perfis já existentes mantêm CRUD no módulo Membros (comportamento anterior)."""
    UserProfile = apps.get_model('usuarios', 'UserProfile')
    for row in UserProfile.objects.all():
        row.papel = 'editor'
        row.modulos = ['membros']
        row.save(update_fields=['papel', 'modulos'])


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_userprofile_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='modulos',
            field=models.JSONField(blank=True, default=list, help_text='Para Comum e Editor, marque os módulos permitidos. Para Admin, este campo é ignorado (acesso total à aplicação).', verbose_name='Módulos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='papel',
            field=models.CharField(choices=[('comum', 'Membro comum'), ('editor', 'Membro editor'), ('admin', 'Membro admin')], default='comum', help_text='Comum: só visualização nos módulos marcados. Editor: criar/editar/excluir nos módulos marcados. Admin: todos os módulos e acesso ao Django Admin (marque também “Staff” ou use este papel).', max_length=20, verbose_name='Papel'),
        ),
        migrations.RunPython(seed_perfil_membros_editor, migrations.RunPython.noop),
    ]
