"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import quote, urlparse, urlunparse

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


def _railway_private_database_url(url: str) -> str:
    """Evita DATABASE_URL com proxy público (*.proxy.rlwy.net) de dentro do Railway."""
    if not url or '.proxy.rlwy.net' not in url:
        return url
    internal_host = (
        os.environ.get('PGHOST', '').strip()
        or os.environ.get('POSTGRES_HOST', '').strip()
    )
    if not internal_host:
        host_guess = os.environ.get('HOST', '').strip()
        if host_guess.endswith('.railway.internal'):
            internal_host = host_guess
    if not internal_host:
        return url
    parsed = urlparse(url)
    if parsed.scheme not in ('postgres', 'postgresql'):
        return url
    user = parsed.username or ''
    password = parsed.password or ''
    auth = ''
    if user:
        auth = f'{quote(user, safe="")}:{quote(password, safe="")}@'
    elif password:
        auth = f':{quote(password, safe="")}@'
    path = parsed.path or '/'
    # Rede privada: sem sslmode=require (quebra com o hostname interno).
    return urlunparse(('postgresql', f'{auth}{internal_host}:5432', path, '', '', ''))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-h2rik63v&n-%asmh9c*=k%od$x!tl3ms*%dpq4*_3l8=4)l*^x',
)

DEBUG = _env_bool('DEBUG', default=True)

_allowed = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
_railway_host = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '').strip()
if _railway_host and _railway_host not in _allowed:
    _allowed.append(_railway_host)

_is_railway = bool(
    os.environ.get('RAILWAY_ENVIRONMENT', '').strip()
    or os.environ.get('RAILWAY', '').strip()
)

if _is_railway:
    # Healthcheck interno (RailwayHealthCheck) usa Host que não é o domínio público.
    ALLOWED_HOSTS = ['*']
else:
    if not _allowed:
        _allowed = ['localhost', '127.0.0.1']
    ALLOWED_HOSTS = list(dict.fromkeys(_allowed))

_csrf_origins = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
if _railway_host:
    _https_origin = f'https://{_railway_host}'
    if _https_origin not in _csrf_origins:
        _csrf_origins.append(_https_origin)
CSRF_TRUSTED_ORIGINS = _csrf_origins


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'dashboard',
    'membros',
    'django_htmx',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_database_url = (
    os.environ.get('DATABASE_PRIVATE_URL', '').strip()
    or os.environ.get('DATABASE_URL', '').strip()
)
if _is_railway and _database_url:
    _database_url = _railway_private_database_url(_database_url)

_postgres_host = (
    os.environ.get('POSTGRES_HOST', '').strip()
    or os.environ.get('PGHOST', '').strip()
)
if not _postgres_host:
    _host_guess = os.environ.get('HOST', '').strip()
    if _host_guess.endswith('.railway.internal'):
        _postgres_host = _host_guess

if _database_url:
    # parse() usa a string; config() lê antes os.environ['DATABASE_URL'] e ignora o rewrite.
    DATABASES = {
        'default': dj_database_url.parse(
            _database_url,
            conn_max_age=600,
            conn_health_checks=True,
        ),
    }
elif _postgres_host:
    _sslmode = os.environ.get('POSTGRES_SSLMODE', 'require').strip()
    _pg_options = {'sslmode': _sslmode} if _sslmode else {}
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'railway'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': _postgres_host,
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
            **({'OPTIONS': _pg_options} if _pg_options else {}),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

if DEBUG:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # No Railway o healthcheck interno chama HTTP; redirect para HTTPS quebra o deploy (502).
    SECURE_SSL_REDIRECT = (not _is_railway) and _env_bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
